---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: aksine-am-com-stg
  namespace: default
spec:
  secretName: aksine-am-com-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.aksine-am.com"
  dnsNames:
  - "aksine-am.com"
  - "*.aksine-am.com"
